apiVersion: batch/v1
kind: Job
metadata:
  name: python-task-runner
spec:
  template:
    spec:
      containers:
      - name: python-task-runner
        image: gcr.io/coxit-test-proj/python-task-runner-image:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-parameters
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-parameters
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: app-parameters
              key: POSTGRES_DB
        - name: ARTIST_NAME
          valueFrom:
            secretKeyRef:
              name: app-parameters
              key: ARTIST_NAME
        imagePullPolicy: Always
        command: ["python", "/app/task_runner.py"]
      restartPolicy: Never
  backoffLimit: 0
