apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-service
spec:
  selector:
    matchLabels:
      app: rest-api-service
  replicas: 1 # You can scale this based on your need
  template:
    metadata:
      labels:
        app: rest-api-service
    spec:
      containers:
      - name: rest-api-service
        image: rest-api-service-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /are-you-up
            port: 5000
          initialDelaySeconds: 15
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
spec:
  ports:
  - port: 60080
    targetPort: 5000
    nodePort: 30080
  selector:
    app: rest-api-service
  type: NodePort
