apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-service
spec:
  selector:
    matchLabels:
      app: rest-api-service
  replicas: 1
  template:
    metadata:
      labels:
        app: rest-api-service
    spec:
      containers:
      - name: rest-api-service
        image: gcr.io/coxit-test-proj/rest-api-service-image:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-parameters
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-parameters
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: app-parameters
              key: POSTGRES_DB
        - name: ARTIST_NAME
          valueFrom:
            secretKeyRef:
              name: app-parameters
              key: ARTIST_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /are-you-up
            port: 5000
          initialDelaySeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
spec:
  ports:
  - port: 60080
    targetPort: 5000
  selector:
    app: rest-api-service
  type: LoadBalancer
